name: Build

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "Direct link to the decrypted IPA"
        default: ""
        required: true
        type: string

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build-ipa:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Revenge Tweak
        run: |
          wget https://github.com/revenge-mod/revenge-tweak/releases/latest/download/io.github.revenge-mod.app_2.0.1_iphoneos-arm.deb
      
      - name: Download Discord IPA
        run: |
          curl -L -o discord.ipa ${{ github.event.inputs.ipa_url }}
          
      - name: Download OpenInDiscord
        run: |
          wget https://raw.githubusercontent.com/daisuke1227/RevengeUpdates/refs/heads/main/OpenDiscordSafariExtension.zip
          unzip -q OpenDiscordSafariExtension.zip

      - name: Add OpenInDiscord
        run: |
          unzip -q discord.ipa
          cp -r OpenDiscordSafariExtension.appex Payload/Discord.app/Plugins/
          
      - name: Download IPA icons
        run: |
          curl -L -o ipa-icons.zip https://raw.githubusercontent.com/pyoncord/assets/main/ipa-icons.zip
          unzip ipa-icons.zip

      - name: Extract Values
        run: |
          PACKAGE=$(grep '^Package:' control | cut -d ' ' -f 2)
          VERSION=$(grep '^Version:' control | cut -d ' ' -f 2)
          echo "APP_NAME=Revenge" >> $GITHUB_ENV

      - name: Install cyan
        run: pip install --force-reinstall https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip Pillow

      - name: Inject tweak - Normal Revenge
        run: |
          cyan -n ${{ env.APP_NAME }} -k PyoncordIcon60x60@2x.png -d -i Payload/Discord.app -o ${{ github.workspace }}/${{ env.APP_NAME }}.ipa -f ${{ github.workspace }}/io.github.revenge-mod.app_1.0.0_iphoneos-arm.deb -usg

      - name: Download DiscordNoTrack
        run: wget https://github.com/asdfzxcvbn/DiscordNoTrack/releases/latest/download/DiscordNoTrack.dylib

      - name: Inject tweak - Revenge + DiscordNoTrack
        run: |
          cyan -n ${{ env.APP_NAME }} -k PyoncordIcon60x60@2x.png -d -i Payload/Discord.app -o ${{ github.workspace }}/${{ env.APP_NAME }}-discordnotrack.ipa -f ${{ github.workspace }}/io.github.revenge-mod.app_1.0.0_iphoneos-arm.deb ${{ github.workspace }}/DiscordNoTrack.dylib -usg

      - name: Upload ipa as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: ${{ github.workspace }}/${{ env.APP_NAME }}.ipa

      - name: Upload ipa-discordnotrack as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipa-discordnotrack
          path: ${{ github.workspace }}/${{ env.APP_NAME }}-discordnotrack.ipa
